# Generated by Django 5.1 on 2024-11-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('id_proveedor', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(max_length=1000000)),
                ('promocion', models.CharField(max_length=30)),
                ('audiencia', models.CharField(max_length=20)),
            ],
        ),
    ]
