# Generated by Django 5.1 on 2024-11-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
