# Generated by Django 5.1 on 2024-11-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=10)),
                ('fecha_registro', models.DateField(verbose_name='Fecha de registro')),
            ],
        ),
    ]
